Human readable

diff --git a/tuxi b/tuxi
--- a/tuxi
+++ b/tuxi
@@ -1,31 +1,56 @@
 #!/usr/bin/env sh
 
-N="\033[0m"; R="\033[1;31m"; G="\033[1;32m"; M="\033[1;35m"; C="\033[1;36m"
+# Colour codes
+N="\033[0m"    # Reset
+R="\033[1;31m" # Red
+G="\033[1;32m" # Green
+M="\033[1;35m" # Magenta
+C="\033[1;36m" # Cyan
 
 help_text() {
-printf "%bUsage:%b tuxi %b<your question>%b\n       tuxi %b<OPTIONS>%b %b<your question>%b\n\n" "$G" "$N" "$M" "$N" "$C" "$N" "$M" "$N"
-cat << EOF
-OPTIONS:
--r, --raw             Simplify Tuxi output. Useful for e.g notify-send.
--h, --help            Displays this help message.
-EOF
-printf "\n%bReport bugs to%b https://github.com/Bugswriter/tuxi\n" "$G" "$N"
+    printf "%bUsage:%b tuxi %b<your question>%b\n\ttuxi %b<OPTIONS>%b %b<your question>%b\n\n" "$G" "$N" "$M" "$N" "$C" "$N" "$M" "$N"
+    printf "%bOPTIONS:%b\n-r, --raw\tSimplify Tuxi output. Useful for e.g notify-send.\n-h, --help\tDisplays this help message.\n" "$G" "$N"
+    printf "\n%bReport bugs to%b https://github.com/Bugswriter/tuxi\n" "$G" "$N"
 }
 
+# Argument parsing
 case $1 in
-    -r|--raw) [ "$2" = "" ] && echo "Please add query!" && exit 1
-              query="$(printf "%s" "$*" | cut -f 2- -d ' ')" && msg() { echo "> $*"; } && err() { echo "$*"; } && strip() { echo "$*"; }
+    -r|--raw)
+        [ -z "$2" ] && echo "Please add query!" && exit 1
+        query="$(printf "%s" "$*" | cut -f 2- -d ' ')"
+	# Raw formatting functions
+        msg() { echo "> $*"; }
+        err() { echo "$*"; }
+        strip() { echo "$*"; }
     ;;
-    -h|--help) help_text && exit 0
+    -h|--help)
+        help_text
+        exit 0
     ;;
-    -*) printf "%bUnknown option%b \"$1\"\n" "$R" "$N" && exit 1
+    -*)
+        printf "%bUnknown option%b \"$1\"\n" "$R" "$N"
+        exit 1
     ;;
-    *) query="$*" && msg() { printf "%b>%b $*\n" "$G" "$N"; } && err() { printf "%b$*%b\n" "$R" "$N"; } && strip() { printf "%b---%b\n$*\n%b---%b\n" "$G" "$N" "$G" "$N"; }
+    *)
+        query="$*"
+	# Normal formatting functions
+        msg() { printf "%b>%b $*\n" "$G" "$N"; } 
+        err() { printf "%b$*%b\n" "$R" "$N"; }
+        strip() { printf "%b---%b\n$*\n%b---%b\n" "$G" "$N" "$G" "$N"; }
     ;;
 esac
 
-checkdep() { [ ! "$(command -v "$*" 2> /dev/null)" ] && err "\"$*\" not found!\n" && exit 1; }
-checkdep "pup"; checkdep "recode"; checkdep "jq"
+# Check if dependencies (pup, recode, jq) are installed.
+checkdep() {
+    while [ -n "$1" ]; do
+        if [ ! "$(command -v $1)" ]; then
+            err "\"$1\" not found!"
+            exit 1
+        fi
+        shift
+    done
+}
+checkdep pup recode jq
 
 [ $# -le 0 ] && echo "Hi, I am Tuxi.. Ask me something" && help_text | head -n1 && exit $?
 
@@ -33,27 +58,27 @@ user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Fi
 
 webpage=$(curl -s -G --compressed "https://www.google.com/search?hl=en_US" --user-agent "$user_agent" --data-urlencode "q=$query")
 
-res0="$(echo "$webpage" | pup 'a.gL9Hy > b text{}' | sed ':a;N;$!ba;s/\n/ /g'| recode html..ISO-8859-1)"
+res0="$(echo "$webpage" | pup 'a.gL9Hy > b text{}' | sed ':a;N;$!ba;s/\n/ /g'| recode html..utf8)"
 [ -n "$res0" ] && msg "u mean $res0?"
 
-list=$(echo "$webpage" | pup 'div.dAassd json{}'  | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..ISO-8859-1)
+list=$(echo "$webpage" | pup 'div.dAassd json{}'  | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..utf8)
 [ -n "$list" ] && strip "$list" && exit
 
-res1="$(echo "$webpage" | pup 'div.zCubwf text{}' | tr -d '\n' | recode html..ISO-8859-1)"
+res1="$(echo "$webpage" | pup 'div.zCubwf text{}' | tr -d '\n' | recode html..utf8)"
 [ -n "$res1" ] && strip "$res1" && exit
 
-res2="$(echo "$webpage" | pup 'div.XcVN5d text{}' | recode html..ISO-8859-1)"
+res2="$(echo "$webpage" | pup 'div.XcVN5d text{}' | recode html..utf8)"
 [ -n "$res2" ] && strip "$res2" && exit
 
-res3="$(echo "$webpage" | pup 'span.hgKElc text{}' | tr -d '\n' | recode html..ISO-8859-1 | tr ' ' '\0' | xargs -0 -n10)"
+res3="$(echo "$webpage" | pup 'span.hgKElc text{}' | tr -d '\n' | recode html..utf8 | tr ' ' '\0' | xargs -0 -n10)"
 [ -n "$res3" ] && strip "$res3" && exit
 
-res4="$(echo "$webpage" | pup 'span.qv3Wpe text{}' | tr -d '\n ' | recode html..ISO-8859-1)"
+res4="$(echo "$webpage" | pup 'span.qv3Wpe text{}' | tr -d '\n ' | recode html..utf8)"
 [ -n "$res4" ] && strip "$res4" && exit
 
-res5="$(echo "$webpage" | pup 'div.bbVIQb text{}' | recode html..ISO-8859-1)"
+res5="$(echo "$webpage" | pup 'div.bbVIQb text{}' | recode html..utf8)"
 [ -n "$res5" ] && strip "$res5" && exit
 
 tmp="$(echo "$webpage" | pup 'div.kno-rdesc')"
 [ -z "$tmp" ] && err "No Result!" && exit 1 || \
-strip "$(echo "$tmp" | pup 'span' | sed -n '2p' | awk '{$1=$1;print}' | recode html..ISO-8859-1 | tr ' ' '\0' | xargs -0 -n10)" 
+strip "$(echo "$tmp" | pup 'span' | sed -n '2p' | awk '{$1=$1;print}' | recode html..utf8 | tr ' ' '\0' | xargs -0 -n10)" 
