think I may have finally quashed all the bash compatability bugs

diff --git a/tuxi b/tuxi
--- a/tuxi
+++ b/tuxi
@@ -4,6 +4,12 @@
 #####      Constants      #####
 ###############################
 
+# my alternative did you mean, requires sd right now, need to tweak it
+alt_dym=true
+if $alt_dym; then
+    [ ! "$(command -v sd)" ] && alt_dym=false
+fi
+
 version="Development"
 LANGUAGE=""
 tuxi_pid="$$"
@@ -22,7 +28,6 @@ tuxi_pid="$$"
 # did_you_mean always needs to be active and top however!
 priority="
 did_you_mean    # did you mean ( eg: linux torvalds ) Because we all know his real name is linux, not linus.
-kno_right       # Knowledge Graph - right ( eg: the office )
 define          # Define ( eg: define Aggrandize )
 kno_val         # Chem facts ( eg: density of silver, density of hydrogen, what is the triple point of oxygen )
 math            # Math ( eg: log_2(3) * pi^e )
@@ -40,6 +45,7 @@ currency        # Currency Conversion ( eg: 1 USD in rupee )
 trans           # Translate ( eg: Vais para cascais? em ingles )
 sport_fixture   # Shows last or next fixture of a sports team ( eg. Chelsea next game )
 rich            # Rich Answers ( eg: elevation of mount everest )
+kno_right       # Knowledge Graph - right ( eg: the office )
 "
 
 ######################################
@@ -198,7 +204,7 @@ debug_info() {
 
 # ensures > did you mean... (if applicable) is printed before any answers
 dym_delay() {
-    while kill -0 "$dym_pid" >/dev/null 2>&1; do [ true ]; done
+    while kill -0 "$dym_pid" 1>/dev/null 2>&1; do [ true ]; done #    haha cpu go brrrrr
 }
 
 # this calls the various snippet functions and checks for valid answers
@@ -209,14 +215,14 @@ test_answers() {
         if ! $quiet; then
             # this needs re-working, there should be a way to do this with regular sed
             # need to figure out how to properly escape the replace string
-            if [ $(command -v sd) ]; then
+            if $alt_dym; then
                 if ! $raw; then
                     corrections="$(echo "$google_html" | pup 'a.gL9Hy text{}')"
                     if [ -n "$corrections" ]; then
                         err_hl="$(echo "$google_html" | pup 'a.gL9Hy > b text{}')"
-                        corrections="$(echo "$corrections" | sed ':a;N;$!ba;s/\n//g' | recode html..ISO-8859-1)"
-                        for errors in $(echo "$err_hl"); do
-                            corrections=$(echo "$corrections" | sd -s "${errors}" "\033[1;96m${errors}\033[1;97m")
+                        corrections="$(printf '%b\n' "$corrections" | sed ':a;N;$!ba;s/\n//g' | recode html..ISO-8859-1)"
+                        for errors in $(printf '%b\n' "$err_hl"); do
+                            corrections=$(printf '%b\n' "$corrections" | sd -s "${errors}" "\033[1;96m${errors}\033[1;97m")
                         done
                         printf "%b>%b \033[3mI'm going to assume you meant\033[0m \033[95m--> \033[1;97m\"%b\"\033[0m\n" "$G" "$N" "$corrections"
                     fi
@@ -399,17 +405,20 @@ query="$*"
 # looking for tuxi_ and updates the priority variable to use only those snippets
 if $pick_search; then
     list_priority="$priority"
-    snippet_check=$(echo "$list_priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^\s*$/d')
+    snippet_check=$(printf '%b\n' "$list_priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^\s*$/d')
     matched=false
     priority="did_you_mean"
-    query="$(echo "$query" | sed 's/ /\\n/g')"
-    for pick_words in $(echo "$query" | grep 'tuxi_' | sed 's/tuxi_//g'); do
-        for check_pick_words in $(echo "$snippet_check"); do
-            [ "$check_pick_words" = "$pick_words" ] && priority="$(printf '%b\n%s\n' "$priority" "$pick_words")" && matched=true
+    query="$(printf '%b\n' "$query" | sed 's/ /\\n/g')"
+    for pick_words in $(printf '%b\n' "$query" | grep 'tuxi_' | sed 's/tuxi_//g'); do
+        for check_pick_words in $(printf '%b\n' "$snippet_check"); do
+            if [ "$check_pick_words" = "$pick_words" ]; then
+                priority="$(printf '%b\n%s\n' "$priority" "$pick_words")"
+                matched=true
+            fi
         done
         if ! $matched; then
             printf "Sorry but %s is not a valid search type\nPlease retry your search using one of the following: tuxi_\n" "$pick_words"
-            printf "%b\n" "$(echo "$list_priority" | sed /did_you_mean/d)"
+            printf "%b\n" "$(printf '%b\n' "$list_priority" | sed /did_you_mean/d)"
             printf "\n"
             printf "If %s is on that list could you please file a bug report, thanks! (and sorry)\n" "$pick_words"
             exit 1
@@ -442,9 +451,9 @@ if $best_match; then
     use_define=false
     use_list=false
 
-    query_check="$(echo "$query" | sed 's/ /\\n/g' | tr '[:upper:]' '[:lower:]')"
-    first_word=$(echo "$query_check" | head -n1)
-    last_word=$(echo "$query_check" | tail -n1)
+    query_check="$(printf '%b\n' "$query" | sed 's/ /\\n/g' | tr '[:upper:]' '[:lower:]')"
+    first_word=$(printf '%b\n' "$query_check" | head -n1)
+    last_word=$(printf '%b\n' "$query_check" | tail -n1)
 
     for keywords in printf '%s\n%s\n' "$first_word" "$last_word"; do
         case "$keywords" in
@@ -463,7 +472,7 @@ if $best_match; then
     $use_cast && priority="$(printf '%b\n' "$priority" | cut -d ' ' -f1 | grep -e 'did_you_mean' -e 'rich' -e 'lists' -e 'kno_')" || j=$(($j - 1))
     $use_define && priority="$(printf '%b\n' "$priority" | cut -d ' ' -f1 | grep -e 'did_you_mean' -e 'define')" || j=$(($j - 1))
     $use_list && priority="$(printf '%b\n' "$priority" | cut -d ' ' -f1 | grep -e 'did_you_mean' -e 'rich' -e 'lists' -e 'kno_')" || j=$(($j - 1))
-    [ $j -eq 0 ] && priority="$(echo "$priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | grep -v 'quotes' | grep -v 'lyrics' | grep -v 'weather')"
+    [ $j -eq 0 ] && priority="$(printf '%b\n' "$priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^[[:space:]]*$/d' | grep -v 'quotes' | grep -v 'lyrics' | grep -v 'weather')"
 fi
 
 # and now we...
@@ -491,9 +500,10 @@ pids=""
 answers_found=0
 printed=0
 if ! $pick_search || ! $best_match; then
-    priority=$(echo "$priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^\$s*$/d')
+    priority=$(printf '%b\n' "$priority" | cut -d ' ' -f1 | sed -e '/^\s*#.*$/d' -e '/^[[:space:]]*$/d')
 fi
-for tests in $(echo "$priority"); do
+
+for tests in $(printf '%b\n' "$priority"); do
     test_answers "$tests" 2>/dev/null &
     if [ -z "$pids" ]; then
         pids="$!"
@@ -509,10 +519,10 @@ done
 laps=0
 while [ $answers_found -eq 0 ]; do
     for waiting1 in $(printf "%b\n" "$pids"); do
-        kill -0 "$waiting1" >/dev/null 2>&1
+        kill -0 "$waiting1" 1>/dev/null 2>&1
         [ $? -eq 0 ] && break
         for waiting2 in $(printf "%b\n" "$pids"); do
-            kill -0 "$waiting2" >/dev/null 2>&1
+            kill -0 "$waiting2" 1>/dev/null 2>&1
             [ $? -eq 0 ] && break 2
         done
         laps=$(($laps + 1))
@@ -529,7 +539,8 @@ done
 if ! $all; then
     until [ $printed -ge 2 ]; do [ true ]; done #    haha cpu go brrrrr
     for kids in $(printf '%b\n' "$pids"); do
-        kill -9 "$kids" >/dev/null 2>&1
+        kill -0 "$kids" 1>/dev/null 2>&1
+        [ $? -ne 0 ] && kill -9 "$kids" 1>/dev/null 2>&1
     done
 fi
 wait
